name: Upload Artifacts of each subdirs
description: Upload Artifacts of each subdirs and keep dir's name
author: owlvisiontech
branding:
  color: red
  icon: upload-cloud

inputs:
  path:
    description: >
      A directory or wildcard pattern that describes what to upload.
    required: true
  if-no-files-found:
    description: >
      The desired behavior if no files are found using the provided path.
      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    default: 'warn'
    required: false
  retention-days:
    description: >
      Duration after which artifact will expire in days. 0 means using default retention.
      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.
    required: false

outputs:
  dirlist:
    description: "directory list in json"
    value: ${{ steps.scan_dirs.outputs.dirlist }}

runs:
  using: 'composite'
  steps:
    - id: scan_dirs
      run : |
        PATH_PREFIX=$INPUT_PATH
        DIRS_JSON=`echo -e "$DIRS_JSON{"`
        DIRS_JSON=`echo -e "$DIRS_JSON\"dirs\":["`

        for  dir  in  $(ls  $PATH_PREFIX)
        do
            if [ -d $PATH_PREFIX/$dir ];then
                echo  $dir
                DIRS_JSON=`echo -e "$DIRS_JSON\
                    {\"name\":\"$dir\",\"path\":\"$PATH_PREFIX/$dir\"},\n"`
            fi
        done

        DIRS_JSON=`echo ${DIRS_JSON%?}`
        DIRS_JSON=`echo -e "$DIRS_JSON]"`
        DIRS_JSON=`echo -e "$DIRS_JSON}"`

        echo $DIRS_JSON > /tmp/dirs.json
        cat /tmp/dirs.json
        echo "::set-output name=dirlist::$(echo $DIRS_JSON)"
      shell: 'bash'
      env:
        INPUT_PATH: ${{ inputs.path }}

    #- id: upload-files
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: ${{ inputs.path }}
    #    path: artifact.tar
    #    if-no-files-found: ${{ inputs.if-no-files-found }}
    #    retention-days: ${{ inputs.retention-days }}

    #- run: rm artifact.tar
    #  shell: 'bash'