name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      id: scan-dirs
      uses: owlvisiontech/upload-artifact-subdir@main
      with:
        path: /home
    - run: echo dirlist ${{ steps.scan-dirs.outputs.dirlist }} 
      shell: bash
    outputs:
     dirlist:  ${{ steps.scan-dirs.outputs.dirlist }} 

  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Scan output:$LAST_OUT"
        shell: 'bash'
    env:
      LAST_OUT: echo ${{ needs.build.outputs.dirlist }}

  upload:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.dirlist)}}
    steps:
    - name: show
      run: echo "-----${{ matrix.name }} ${{ matrix.path }}"
      shell: bash

    - name: upload files
      id: upload-files
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.path }}
