name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      uses: owlvisiontech/upload-artifact-subdir@main
      with:
        path: /home/

  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ jobs.build.outputs.dirlist }}

  upload:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(jobs.build.outputs.dirlist)}}
    steps:
    - name: upload files
      id: upload-files
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.path }}
        if-no-files-found: ${{ inputs.if-no-files-found }}
        retention-days: ${{ inputs.retention-days }}

